/** All interactive muscle SVG IDs in the body map (detailed muscle view) */
export const INTERACTIVE_MUSCLE_IDS = [
  'upper-trapezius',
  'neck',
  'gastrocnemius',
  'tibialis',
  'soleus',
  'outer-quadricep',
  'rectus-femoris',
  'inner-quadricep',
  'inner-thigh',
  'wrist-extensors',
  'wrist-flexors',
  'long-head-bicep',
  'short-head-bicep',
  'obliques',
  'lower-abdominals',
  'upper-abdominals',
  'mid-lower-pectoralis',
  'upper-pectoralis',
  'anterior-deltoid',
  'lateral-deltoid',
  'medial-hamstrings',
  'lateral-hamstrings',
  'gluteus-maximus',
  'gluteus-medius',
  'lowerback',
  'lats',
  'medial-head-triceps',
  'long-head-triceps',
  'lateral-head-triceps',
  'posterior-deltoid',
  'lower-trapezius',
  'traps-middle',
  // Group view IDs (simplified muscle groups used in group SVGs)
  'calves',
  'quads',
  'hamstrings',
  'glutes',
  'abdominals',
  'chest',
  'biceps',
  'triceps',
  'forearms',
  'shoulders',
  'traps',
  'back',
  'adductors',
  'abductors',
] as const;

export type InteractiveMuscleId = typeof INTERACTIVE_MUSCLE_IDS[number];
