export const PROMOTE_INCREASE_WEIGHT: readonly string[] = [
  'At ~{topWeight}, you hit at least {minReps} reps, keep this load until you can repeat {targetReps}+ reps, then move to ~{nextWeight}',
  'Top sets reached {minReps} reps at ~{topWeight}, stabilize at {targetReps}+ reps first, then move to ~{nextWeight}',
  'Performance is stable at ~{topWeight}, keep pushing to {targetReps}+ reps before moving to ~{nextWeight}',
  'You completed the target reps, rebuild consistency at ~{topWeight}, then move to ~{nextWeight}',
  'You are above target at top weight, lock in {targetReps}+ reps at ~{topWeight}, then use ~{nextWeight}',
  'Reps are strong at ~{topWeight}, hold this weight until {targetReps}+ reps are consistent, then move to ~{nextWeight}',
  'You have headroom, keep ~{topWeight} and use {targetReps}+ reps as the checkpoint before ~{nextWeight}',
  'Current output supports progression, maintain ~{topWeight}, hit {targetReps}+ reps, then go to ~{nextWeight}',
  'Strength is ready for more, stay at ~{topWeight} until you hit {targetReps}+ reps consistently, then progress to ~{nextWeight}',
  'Your numbers support the next step, lock in {targetReps}+ reps at ~{topWeight}, then move to ~{nextWeight}',
  'Ready to advance, hold at ~{topWeight} and build to {targetReps}+ reps, then jump to ~{nextWeight}',
  'You have earned the right to progress, cement {targetReps}+ reps at ~{topWeight}, then use ~{nextWeight}',
  'Progression signals are strong, maintain ~{topWeight}, hit {targetReps}+ reps, then advance to ~{nextWeight}',
  'Your strength has grown, secure {targetReps}+ reps at ~{topWeight}, then progress to ~{nextWeight}',
  'Capacity has increased, build consistency at {targetReps}+ reps with ~{topWeight}, then move to ~{nextWeight}',
  'It is time to level up, stabilize at ~{topWeight} with {targetReps}+ reps, then go to ~{nextWeight}',
  'Building toward more, hold at ~{topWeight} and reach {targetReps}+ reps consistently, then add ~{nextWeight}',
  'Progress is in sight, lock in {targetReps}+ reps at ~{topWeight}, then make the jump to ~{nextWeight}',
  'You are ready, get {targetReps}+ reps at ~{topWeight}, then progress to ~{nextWeight}',
  'Strength gains support it, maintain ~{topWeight} until {targetReps}+ reps, then advance to ~{nextWeight}',
  'You crushed it at ~{topWeight}, lock in {targetReps}+ reps, then move to ~{nextWeight}',
  'Great performance, hold ~{topWeight} for {targetReps}+ reps, then go to ~{nextWeight}',
  'Strong output, stay at ~{topWeight} until {targetReps}+ reps feel easy, then add ~{nextWeight}',
  'You are ready for more, build to {targetReps}+ reps at ~{topWeight}, then progress',
  'Time to move up, hit {targetReps}+ reps at ~{topWeight}, then use ~{nextWeight}',
  'Your work is done at this weight, aim for {targetReps}+ reps at ~{topWeight}, then advance',
  'Solid progress shown, maintain ~{topWeight} until {targetReps}+ reps, then jump',
  'Ceiling hit, stay at ~{topWeight} and hit {targetReps}+ reps before adding ~{nextWeight}',
  'Load controlled, lock in {targetReps}+ reps at ~{topWeight}, then progress to ~{nextWeight}',
  'Consistency achieved, build to {targetReps}+ reps at ~{topWeight}, then move up',
  'Foundation set, hold ~{topWeight} for {targetReps}+ reps, then use ~{nextWeight}',
  'Ready for progression, hit {targetReps}+ reps at ~{topWeight}, then advance',
];

export const DEMOTE_TOO_HEAVY: readonly string[] = [
  'Top-set output is only {minReps} reps, use ~{topWeight} and rebuild to {targetReps} reps before moving back to ~{nextWeight}',
  'Load is limiting quality reps, use ~{topWeight} and target {targetReps} reps, then move to ~{nextWeight}',
  'You are capped by current load, repeat ~{topWeight} until {targetReps} reps are repeatable, then move up to ~{nextWeight}',
  'Current set quality is low, use ~{topWeight}, rebuild to {targetReps} reps first, then return to ~{nextWeight}',
  'Recovery cost is high at this load, use ~{topWeight}, hit {targetReps} reps, then progress to ~{nextWeight}',
  'Rep output is too low, standardize at ~{topWeight} and hold {targetReps} reps before trying ~{nextWeight}',
  'Too heavy for productive execution right now, use ~{topWeight}, reach {targetReps} reps, then move up',
  'Capacity is lagging load, repeat ~{topWeight} and rebuild to {targetReps} reps before the next jump to ~{nextWeight}',
  'This weight is holding you back, drop to ~{topWeight} and build to {targetReps} reps, then try ~{nextWeight}',
  'Quality is suffering at this load, use ~{topWeight}, get solid {targetReps} reps, then progress to ~{nextWeight}',
  'Your body is not ready for this weight, build at ~{topWeight} until you hit {targetReps} reps consistently',
  'The load is too demanding right now, reset at ~{topWeight} and establish {targetReps} reps again',
  'You are being limited by the weight, drop to ~{topWeight} and strengthen your foundation first',
  'Form is likely breaking down, use ~{topWeight} and focus on clean {targetReps} reps before adding load',
  'Strength needs to catch up to this weight, rebuild at ~{topWeight} with {targetReps} solid reps',
  'The jump was too aggressive, take a step back to ~{topWeight} and rebuild to {targetReps} reps',
  'Your body needs time at this level, hold ~{topWeight} and hit {targetReps} reps before progressing',
  'The weight is exceeding your capacity, reset to ~{topWeight} and establish {targetReps} reps',
  'Load is the limiting factor now, use ~{topWeight} and build consistent {targetReps} reps',
  'You have jumped too far ahead, return to ~{topWeight} and consolidate strength at {targetReps} reps',
  'Intensity is ahead of strength right now, use ~{topWeight}, build to {targetReps} reps, then go to ~{nextWeight}',
  'Too heavy right now, drop to ~{topWeight} and rebuild to {targetReps} reps',
  'Weight needs to come down, use ~{topWeight} and hit {targetReps} reps before trying more',
  'Load is too high, reset at ~{topWeight} and work back up to {targetReps} reps',
  'This weight is not working, go back to ~{topWeight} and establish {targetReps} reps',
  'Too demanding, drop to ~{topWeight} and build a base of {targetReps} reps',
  'Weight exceeding strength, reset to ~{topWeight} and rebuild {targetReps} reps',
  'Form is breaking down, use ~{topWeight} and focus on clean {targetReps} reps',
  'Capacity not there yet, drop to ~{topWeight} and strengthen first',
  'Not ready for this load, go back to ~{topWeight} and hit {targetReps} reps',
  'Overreached on weight, return to ~{topWeight} and rebuild {targetReps} reps',
  'Strength not matching the load, use ~{topWeight} and build to {targetReps} reps',
];

export const DEMOTE_INCONSISTENT: readonly string[] = [
  'Rep spread is too wide ({minReps}-{maxReps}), pick {targetReps} reps and keep ~{topWeight} for consistency',
  'Performance fluctuates set to set, anchor at {targetReps} reps with ~{topWeight}, then move to ~{nextWeight} once repeatable',
  'Load control is inconsistent, keep ~{topWeight} and hold {targetReps} reps across sets before trying ~{nextWeight}',
  'Output variability is high, lock in {targetReps} reps at ~{topWeight}, then increase to ~{nextWeight}',
  'Progress is harder with scattered reps, choose {targetReps} reps and standardize at ~{topWeight}',
  'Set quality is uneven, tighten to {targetReps} reps with ~{topWeight}, then move up to ~{nextWeight}',
  'Consistency is the bottleneck, repeat {targetReps} reps at ~{topWeight} first, then move to ~{nextWeight}',
  'You are all over the place with reps, get {targetReps} steady reps at ~{topWeight} before adding weight',
  'Reps are bouncing around too much, focus on {targetReps} consistent reps at ~{topWeight}',
  'Variable output is holding you back, build a baseline of {targetReps} reps at ~{topWeight}',
  'Your rep counts need to stabilize, hold ~{topWeight} and hit {targetReps} reps on every set',
  'Inconsistent performance is the issue, standardize at ~{topWeight} with {targetReps} reps',
  'You need to tighten up, get {targetReps} reliable reps at ~{topWeight} before progressing',
  'Scattered reps mean inconsistent training, lock in {targetReps} reps at ~{topWeight}',
  'The pattern needs to tighten, maintain ~{topWeight} and achieve {targetReps} reps consistently',
  'Your reps need to converge, work at ~{topWeight} until you hit {targetReps} on most sets',
  'Focus on steadiness before adding load, get {targetReps} reps at ~{topWeight} consistently',
  'Build reliability before progression, establish {targetReps} reps at ~{topWeight}',
  'Variable output is a sign to consolidate, hold at ~{topWeight} until {targetReps} reps feel normal',
  'Stabilize before you advance, build {targetReps} steady reps at ~{topWeight}',
  'Consistency builds strength, focus on {targetReps} reps at ~{topWeight} without fluctuation',
  'Get your reps aligned, aim for {targetReps} at ~{topWeight} every single set',
  'Your sets are too different, aim for {targetReps} reps at ~{topWeight} each time',
  'Reps are all over the place, get steady at {targetReps} with ~{topWeight}',
  'Output varies too much, lock in {targetReps} reps at ~{topWeight}',
  'Sets are inconsistent, build to {targetReps} reps steadily at ~{topWeight}',
  'You need uniform output, hit {targetReps} reps at ~{topWeight} on every set',
  'Variability is high, settle on {targetReps} reps at ~{topWeight}',
  'Reps need to converge, get {targetReps} steady reps at ~{topWeight}',
  'Unsteady performance, aim for {targetReps} consistent reps at ~{topWeight}',
  'Work on steadiness, hit {targetReps} reps at ~{topWeight} uniformly',
  'Your rep counts vary too much, lock in {targetReps} at ~{topWeight}',
];
