import type { SetCommentaryOptions } from './setCommentaryLibrary';

export const WEIGHT_INCREASE_EXCEEDED: SetCommentaryOptions = {
  shortMessages: [
    'Crushed It',
    'Overdelivered',
    'Exceeded',
    'Stronger Than Expected',
    'Beyond Target',
    'More in the Tank',
    'Handled With Ease',
    'Cleared the Bar',
    'Better Than Plan',
    'Outperformed',
    'Walked Through',
    'Made It Look Easy',
  ] as const,
  tooltips: [
    '{reps} reps at +{weight}kg',
    'Exceeded goal: {reps} reps',
    'More than planned: {reps}',
    'Stronger: {reps} reps',
    'Over target: {reps}',
    '{reps} reps, goal surpassed',
    'Weight too easy: {reps}',
    'Cleared target by {reps}',
    'Extra reps: {reps}',
    'Beyond plan: {reps}',
    'Way ahead: {reps}',
    'Exceeded: {reps}',
  ] as const,
  whyLines: [
    'Strength up noticeably',
    'Weight was too light',
    'Recovery was strong',
    'Adaptation kicked in',
    'Power output increased',
    'Progress exceeded expectations',
    'This weight is now comfortable',
    'Time to move up',
    'Form held easily',
    'Energy reserves high',
    'Previous training paid off',
    'Fresh and ready today',
  ] as const,
  improveLines: [
    'Increase weight by 2.5kg next time',
    'This weight is too easy, add load',
    'You are ready for progression',
    'Move up in weight next session',
    'Add 5kg and rebuild reps',
    'Strong work, keep pushing',
    'Time to challenge yourself more',
    'Your strength is ahead of this load',
    'Hold here for a session then add more',
    'Lock in these reps at the new weight',
    'Build consistency at heavier weight',
    'Keep this momentum going',
  ] as const,
};

export const WEIGHT_INCREASE_MET: SetCommentaryOptions = {
  shortMessages: [
    'Goal Met',
    'Right on Target',
    'On Plan',
    'Perfect Match',
    'Target Hit',
    'Right There',
    'As Planned',
    'Nailed It',
    'Exact Match',
    'Plan Delivered',
    'Executed',
    'Done',
  ] as const,
  tooltips: [
    '{reps} reps at +{weight}kg',
    'Target hit: {reps} reps',
    'As planned: {reps} reps',
    'Goal met: {reps} reps',
    '{reps} reps on plan',
    'Perfect execution: {reps}',
    'Right at goal: {reps}',
    'Exact target: {reps}',
    'Matched plan: {reps}',
    'Weight increase met',
    'Nailed: {reps}',
    'Executed: {reps}',
  ] as const,
  whyLines: [
    'Progress on track',
    'Strength matched plan',
    'Good execution',
    'Appropriate weight jump',
    'Recovery supported progress',
    'Plan pacing is right',
    'Strength adapting well',
    'Consistent performance',
    'Target load achieved',
    'Progression working',
    'Perfect weight selection',
    'Load matched ability',
  ] as const,
  improveLines: [
    'Hold this weight for another session',
    'Aim to add 1 rep next time',
    'Build consistency before adding more',
    'This is the sweet spot, stay here',
    'Lock in these reps then progress',
    'Keep this weight until it feels easy',
    'Perfect, this is where growth happens',
    'Maintain this level for 2-3 sessions',
    'Your progression is working',
    'Trust the process',
    'Focus on quality at this load',
    'Build a base before adding',
  ] as const,
};

export const WEIGHT_INCREASE_SLIGHTLY_BELOW: SetCommentaryOptions = {
  shortMessages: [
    'Close Call',
    'Nearly There',
    'Just Missed',
    'Slightly Below',
    'Almost Hit',
    'Near Target',
    'Right Behind',
    'One Rep Short',
    'Almost On Plan',
    'Slightly Off',
    'So Close',
    'Almost',
  ] as const,
  tooltips: [
    '{reps} reps (target {target})',
    'Just short: {reps} reps',
    'Near target: {reps}',
    'Almost hit: {reps}',
    '{reps} reps, close',
    'Slightly under: {reps}',
    'Close call: {reps}',
    'One rep off: {reps}',
    'Near goal: {reps}',
    'Almost: {reps}',
    'So close: {reps}',
    'Just shy: {reps}',
  ] as const,
  whyLines: [
    'Small gap to target',
    'Strength is almost there',
    'Recovery slightly off',
    'Energy dipped near end',
    'Close to plan',
    'Minor adjustment needed',
    'Almost ready to progress',
    'Need a bit more rest',
    'Just a bit more strength',
    'Nearly on track',
    'Fatigue limited last rep',
    'Close but not quite',
  ] as const,
  improveLines: [
    'Add a little more rest',
    'Keep the weight and aim to hit target next time',
    'Focus on clean reps',
    'Increase recovery before this set',
    'Take 2 extra minutes rest',
    'Try one more deep breath before starting',
    'Set a firm goal of hitting the target',
    'Focus on steady speed on each rep',
    'Reset your grip if needed',
    'Walk around briefly before set',
    'Stay hydrated',
    'Trust that one more rep is there',
  ] as const,
};

export const WEIGHT_INCREASE_SIGNIFICANTLY_BELOW: SetCommentaryOptions = {
  shortMessages: [
    'Too Heavy',
    'Overreached',
    'Big Drop',
    'Missed Target',
    'Load Too High',
    'Needs Adjustment',
    'Not There Yet',
    'Underperformed',
    'Weight Jump Too Big',
    'Step Back Needed',
    'Too Aggressive',
    'Not Ready',
  ] as const,
  tooltips: [
    '{reps} reps (target {target})',
    'Below target: {reps}',
    'Missed by a lot: {reps}',
    'Too heavy: {reps}',
    'Significantly under: {reps}',
    'Load too high: {reps}',
    'Big miss: {reps}',
    'Not ready: {reps}',
    'Drop in reps: {reps}',
    'Weight jump too much',
    'Way off: {reps}',
    'Huge gap: {reps}',
  ] as const,
  whyLines: [
    'Weight increase too aggressive',
    'Strength not ready for jump',
    'Recovery insufficient',
    'Energy was low',
    'Fatigue too high',
    'Load exceeded capacity',
    'Need smaller increment',
    'Overreached slightly',
    'Muscle endurance limited',
    'Progression needs adjustment',
    'Strength gap remains',
    'Jumped too far too soon',
  ] as const,
  improveLines: [
    'Use a smaller jump on the next attempt',
    'Keep this load only if reps recover quickly',
    'Take more rest before your top set',
    'Build reps at slightly lower weight first',
    'Drop back to previous weight',
    'Build at current weight for another session',
    'Go back 2.5kg and rebuild',
    'Stay at previous weight until consistent',
    'Master this weight before progressing',
    'Build your base stronger first',
    'Focus on form at this load',
    'Take 3 minutes between heavy sets',
  ] as const,
};
