import type { SetCommentaryOptions } from './setCommentaryLibrary';

export const SAME_WEIGHT_REPS_INCREASED: SetCommentaryOptions = {
  shortMessages: [
    'Found More',
    'Pushed Through',
    'More Reps',
    'Energy Returned',
    'Got Stronger',
    'Turned Around',
    'Building Momentum',
    'Pushing Forward',
    'More Left',
    'Got Going',
    'Bounced Back',
    'Gained Ground',
  ] as const,
  tooltips: [
    '+{diff} reps vs last',
    'Found {diff} more reps',
    'Recovery helped +{diff}',
    '+{diff} reps: reserves found',
    'Energy returned +{diff}',
    'Better rest paid off +{diff}',
    'Got blood flowing +{diff}',
    'Warmed into it +{diff}',
    'Hit your stride +{diff}',
    'Found rhythm +{diff}',
    'Pushed through +{diff}',
    'Finished strong +{diff}',
  ] as const,
  whyLines: [
    'Had reserves left in the tank',
    'Took longer rest this time',
    'Better recovery between sets',
    'Pacing improved',
    'Found extra energy',
    'Recovery worked well',
    'Fatigue was managed',
    'Rest time helped',
    'Body adapted to the work',
    'Energy levels bounced back',
    'Mental focus sharpened',
    'Got into the flow',
  ] as const,
  improveLines: [
    'Keep the longer rest to sustain this',
    'You have more in the tank, push harder',
    'Start with this intensity from set one',
    'Your body responds well to longer rest',
    'Try to replicate this from the start',
    'Warm up more thoroughly next time',
    'Focus on steady breathing at set start',
    'Keep effort consistent across all sets',
    'Add another set at this level if possible',
  ] as const,
};

export const SAME_WEIGHT_REPS_SAME: SetCommentaryOptions = {
  shortMessages: [
    'Consistent',
    'Steady',
    'Solid',
    'On Track',
    'Holding',
    'Stable',
    'Even Output',
    'Matched',
    'Same Level',
    'Tied',
    'Repeated',
    'Maintained',
  ] as const,
  tooltips: [
    'Maintained {reps} reps',
    'Steady: {reps} reps',
    'Held: {reps} reps',
    'Stable: {reps} reps',
    'Even output: {reps}',
    'Consistent: {reps} reps',
    'Matched last set',
    'Same performance',
    'Held steady',
    'Level output: {reps}',
    'Locked in: {reps}',
    'Controlled: {reps}',
  ] as const,
  whyLines: [
    'Good pacing and recovery',
    'Rest time worked well',
    'Fatigue managed perfectly',
    'Pacing was on point',
    'Recovery between sets solid',
    'Energy levels stable',
    'Technique stayed consistent',
    'Breathing was steady',
    'Focus maintained well',
    'Workload distributed evenly',
    'Rest periods were optimal',
    'You knew what to expect',
  ] as const,
  improveLines: [
    'Try to push for one more rep',
    'Increase weight slightly next time',
    'You could add a little more load',
    'Aim for progressive overload',
    'Build volume before adding weight',
    'Your base is solid, you can push more',
    'Consider adding a light set at the end',
    'Try to add a rep to each set',
  ] as const,
};

export const SAME_WEIGHT_DROP_MILD: SetCommentaryOptions = {
  shortMessages: [
    'Normal Fatigue',
    'Expected Drop',
    'Standard Decline',
    'Typical Fatigue',
    'Working Hard',
    'On Track',
    'Fatigue Setting In',
    'Expected Loss',
    'Normal Pattern',
    'Slight Dip',
    'Minor Drop',
    'Gradual Decline',
  ] as const,
  tooltips: [
    '-{dropAbs} reps ({dropPct}%)',
    '-{dropAbs} reps: normal',
    '-{dropAbs} reps: expected',
    '-{dropAbs}: standard fatigue',
    '-{dropAbs}: working hard',
    'Normal: -{dropAbs} reps',
    '-{dropAbs}: typical drop',
    '-{dropAbs}: expected decline',
    '-{dropAbs}: mild fatigue',
    '-{dropAbs}: within normal range',
    '-{dropAbs}: on track',
    '-{dropAbs}: slight dip',
  ] as const,
  whyLines: [
    'Normal fatigue pattern',
    'Expected decline over sets',
    'Standard endurance limits',
    'Typical drop-off',
    'Fatigue buildup is normal',
    'Working within normal range',
    'Pacing is consistent',
    'Effort level appropriate',
    'Energy dropping as expected',
    'Normal set-to-set decline',
    'Work capacity holding steady',
    'This is what hard work looks like',
  ] as const,
  improveLines: [
    'Add 30 seconds to your rest',
    'Pace slower on the first sets',
    'Focus on deep breathing between sets',
    'Take one deep breath before starting',
    'Walk around briefly between sets',
    'Stay hydrated, drink water',
    'Focus on setup before each rep',
    'Take your time with setup',
    'Use consistent speed on each rep',
    'Focus on one rep at a time',
    'Add 30s rest next time',
    'Try 2 minutes rest before this set',
  ] as const,
};

export const SAME_WEIGHT_DROP_MODERATE: SetCommentaryOptions = {
  shortMessages: [
    'Fatigue Building',
    'Energy Dip',
    'Feeling It',
    'Working Hard',
    'Form Holding',
    'Tiring Out',
    'Noticeable Drop',
    'Grinding',
    'Pushing Through',
    'Under Strain',
    'Holding On',
    'Digging Deep',
  ] as const,
  tooltips: [
    '-{dropAbs} reps ({dropPct}%)',
    '-{dropAbs}: fatigue building',
    '-{dropAbs}: holding on',
    '-{dropAbs}: still solid',
    '-{dropAbs}: getting tired',
    '-{dropAbs}: moderate drop',
    '-{dropAbs}: energy fading',
    '-{dropAbs}: fatigue set in',
    '-{dropAbs}: effort rising',
    '-{dropAbs}: pushing through',
    '-{dropAbs}: grinding',
    '-{dropAbs}: tiring out',
  ] as const,
  whyLines: [
    'Fatigue building up',
    'Energy reserves dropping',
    'Effort rising each set',
    'Still within normal range',
    'Work capacity challenged',
    'Pacing could be tighter',
    'Rest might need more time',
    'Strength curve declining',
    'Muscle endurance taxed',
    'Energy management needed',
    'Form still holding',
    'Pushing through fatigue',
  ] as const,
  improveLines: [
    'Take longer rest between sets',
    'Keep the same load and lose fewer reps next set',
    'Use steadier speed to preserve output',
    'Take 2-3 deep breaths before the next set',
    'Walk around briefly between sets',
    'Stay hydrated',
    'Focus on steady breathing: inhale, exhale',
    'Reset your grip between reps',
    'Focus on steady effort',
    'Set a goal for the next set',
    'Take 3 minutes rest before next heavy set',
    'Keep this weight and rebuild reps',
  ] as const,
};

export const SAME_WEIGHT_DROP_SEVERE: SetCommentaryOptions = {
  shortMessages: [
    'Fatigue Spike',
    'Big Drop',
    'Energy Crash',
    'Deep Fatigue',
    'Overreached',
    'Major Dip',
    'Empty Tank',
    'Needs Rest',
    'System Drained',
    'Done',
    'Wiped Out',
    'Maxed Out',
  ] as const,
  tooltips: [
    '-{dropAbs} reps ({dropPct}%)',
    '-{dropAbs}: big drop',
    '-{dropAbs}: fatigue spike',
    '-{dropAbs}: heavy fatigue',
    '-{dropAbs}: needs recovery',
    '-{dropAbs}: deep fatigue',
    '-{dropAbs}: energy crash',
    '-{dropAbs}: tank empty',
    '-{dropAbs}: too steep',
    '-{dropAbs}: major dip',
    '-{dropAbs}: total fatigue',
    '-{dropAbs}: heavy toll',
  ] as const,
  whyLines: [
    'Fatigue accumulated quickly',
    'Energy reserves depleted',
    'Rest time too short',
    'Set intensity too high',
    'Endurance limit reached',
    'Fatigue hit hard',
    'Too much too soon',
    'Energy management needed',
    ' incompleteRecovery',
    'Strength not ready for this load',
    'Body needs a reset',
    'System overloaded',
  ] as const,
  improveLines: [
    'Add more rest before hard sets',
    'Use slightly lighter weight for this exercise',
    'Stop 1 rep before form breaks',
    'Take 3-5 minutes before next heavy set',
    'Reduce the weight',
    'Focus on quality over reps',
    'Do fewer sets at this level',
    'Save energy for quality sets',
    'Stop 1-2 reps before failure',
    'Use controlled reps',
    'Build back gradually',
  ] as const,
};
