import type { SetCommentaryOptions } from './setCommentaryLibrary';

export const WEIGHT_DECREASE_MET: SetCommentaryOptions = {
  shortMessages: [
    'Adjusted Well',
    'Right Call',
    'Smart Drop',
    'Recovery Focus',
    'Good Reset',
    'Handled It',
    'Controlled Cut',
    'Back on Track',
    'Balance Restored',
    'Fatigue Managed',
    'Right Adjustment',
    'Good Choice',
  ] as const,
  tooltips: [
    '{reps} reps after drop',
    'Weight drop met: {reps}',
    'Adjustment worked: {reps}',
    'Smart drop: {reps}',
    'Recovered reps: {reps}',
    'Reset success: {reps}',
    'Drop paid off: {reps}',
    'Good call: {reps}',
    'Recovery set: {reps}',
    'Managed well: {reps}',
    'Well handled: {reps}',
    'Good reset: {reps}',
  ] as const,
  whyLines: [
    'Drop let you recover',
    'Good call adjusting',
    'Energy restored',
    'Fatigue managed well',
    'Technique held steady',
    'Reset helped performance',
    'Smarter pacing',
    'Right adjustment',
    'Momentum rebuilt',
    'Strength stabilized',
    'Managed fatigue',
    'Recovery effective',
  ] as const,
  improveLines: [
    'This was smart, listen to your body',
    'Use this as a model for future adjustments',
    'You made a good call, trust this feeling',
    'Match reps from this set next time',
    'Build toward matching this at heavier weight',
    'Keep this weight and add reps next time',
    'This is a sustainable approach',
    'Recovery-oriented training works',
    'This shows good self-awareness',
    'Build consistency at this weight',
    'Hold this for a session or two',
    'You can progress from here',
  ] as const,
};

export const WEIGHT_DECREASE_SLIGHTLY_BELOW: SetCommentaryOptions = {
  shortMessages: [
    'Still Heavy',
    'Not Quite',
    'Needs More Drop',
    'Close',
    'Almost Recovered',
    'Slightly Low',
    'Not Fully Reset',
    'Still Struggling',
    'Near Recovery',
    'Almost There',
    'Needs More Rest',
    'Partial Reset',
  ] as const,
  tooltips: [
    '{reps} reps after drop',
    'Still short: {reps}',
    'Not enough: {reps}',
    'Close but low: {reps}',
    'Recovery not full: {reps}',
    'Drop insufficient: {reps}',
    'Almost recovered: {reps}',
    'Still heavy: {reps}',
    'Partial reset: {reps}',
    'Need more drop',
    'Close to recovery: {reps}',
    'Not quite: {reps}',
  ] as const,
  whyLines: [
    'Fatigue still high',
    'Drop not enough',
    'Recovery incomplete',
    'Strength still down',
    'Need more rest',
    'Energy still low',
    'Adjustment insufficient',
    'Consider larger drop',
    'Still fatigued',
    'Body not fully recovered',
    'Reset partially worked',
    'Strength not back yet',
  ] as const,
  improveLines: [
    'Drop weight a bit more',
    'Add extra rest before this set',
    'Keep this load and aim to match reps on the next set',
    'Focus on steady effort',
    'Stop 1 rep before form breaks to keep quality high',
    'Consider dropping slightly more weight',
    'Take 2 more minutes rest',
    'Focus on quality over quantity',
    'Use controlled reps',
    'Reset between reps',
    'Focus on setup before each rep',
    'Take your time between sets',
  ] as const,
};

export const WEIGHT_DECREASE_SIGNIFICANTLY_BELOW: SetCommentaryOptions = {
  shortMessages: [
    'Fatigue High',
    'Drop Not Enough',
    'Still Heavy',
    'Needs More Reset',
    'Overworked',
    'Big Fatigue',
    'Strength Down',
    'Too Taxing',
    'Deep Fatigue',
    'Total Fatigue',
    'Wiped Out',
    'Done',
  ] as const,
  tooltips: [
    '{reps} reps after drop',
    'Still too heavy: {reps}',
    'Fatigue high: {reps}',
    'Drop not enough: {reps}',
    'Major fatigue: {reps}',
    'Not recovered: {reps}',
    'Needs more drop',
    'Too taxing: {reps}',
    'Still heavy load',
    'Strength down',
    'Deep fatigue',
    'Too much today',
  ] as const,
  whyLines: [
    'Fatigue still very high',
    'Recovery insufficient',
    'Drop was too small',
    'Strength significantly down',
    'Body needs more rest',
    'Set-to-set fatigue is limiting output right now',
    'Energy depleted',
    'Too much too soon',
    'Need deeper reset',
    'Training stress high',
    'Not recovered from previous work',
    'System overloaded',
  ] as const,
  improveLines: [
    'Reduce load further',
    'Take longer rest before repeating this effort',
    'Use controlled reps and keep form strict',
    'Treat the next set as a quality set',
    'Rebuild reps gradually before adding weight',
    'Drop significantly more weight',
    'Consider dropping 15-20%',
    'Take 5 minutes before next set',
    'Maybe move to lighter work instead',
    'Focus on quality, not intensity',
    'Save energy for another day',
    'Build back slowly',
  ] as const,
};
