// Filler words to remove during fingerprinting
export const FILLER_WORDS = new Set([
  'a', 'an', 'the', 'with', 'and', 'or', 'to', 'on', 'in', 'of', 'for', 'at', 'from',
  'using', 'version', 'v', 'var', 'variation', 'style', 'type',
]);

// Equipment words - tracked separately for equipment-agnostic matching
export const EQUIPMENT_WORDS = new Set([
  'dumbbell', 'dumbbells', 'db',
  'barbell', 'bb', 'bar',
  'kettlebell', 'kb',
  'cable', 'cables',
  'machine', 'lever', 'selectorized',
  'band', 'bands', 'resistance',
  'bodyweight', 'bw', 'body', 'weight',
  'smith', 'smiths',
  'ez', 'ezbar', 'curlbar',
  'suspension', 'trx',
  'plate', 'plates', 'weighted',
  'assisted',
  'none', 'other',
]);

// Word synonyms - map variations to canonical forms
export const WORD_SYNONYMS: Record<string, string> = {
  // Body parts
  'bicep': 'biceps',
  'tricep': 'triceps',
  'lat': 'lats',
  'pec': 'chest',
  'pecs': 'chest',
  'pectoral': 'chest',
  'quad': 'quadriceps',
  'quads': 'quadriceps',
  'ham': 'hamstrings',
  'hams': 'hamstrings',
  'hamstring': 'hamstrings',
  'glute': 'glutes',
  'calf': 'calves',
  'ab': 'abdominals',
  'abs': 'abdominals',
  'abdominal': 'abdominals',
  'delt': 'deltoid',
  'delts': 'deltoids',
  'trap': 'traps',
  'trapezius': 'traps',

  // Exercise variations
  'pulldown': 'pulldown',
  'pull-down': 'pulldown',
  'pushdown': 'pushdown',
  'push-down': 'pushdown',
  'pushup': 'pushup',
  'push-up': 'pushup',
  'pullup': 'pullup',
  'pull-up': 'pullup',
  'chinup': 'chinup',
  'chin-up': 'chinup',
  'deadlift': 'deadlift',
  'dead-lift': 'deadlift',
  'benchpress': 'benchpress',
  'bench-press': 'benchpress',

  // Equipment
  'db': 'dumbbell',
  'dumbbells': 'dumbbell',
  'bb': 'barbell',
  'kb': 'kettlebell',
  'ez-bar': 'ezbar',
  'ez': 'ezbar',
  'curlbar': 'ezbar',
  'curl-bar': 'ezbar',

  // Descriptors
  'inclined': 'incline',
  'declined': 'decline',
  'seated': 'seated',
  'sitting': 'seated',
  'standing': 'standing',
  'lying': 'lying',
  'prone': 'lying',
  'supine': 'lying',
  'single': 'single',
  'one': 'single',
  'unilateral': 'single',
  'double': 'double',
  'two': 'double',
  'bilateral': 'double',
  'alternate': 'alternating',
  'alternated': 'alternating',
  'reverse': 'reverse',
  'reversed': 'reverse',

  // Actions
  'curl': 'curl',
  'curls': 'curl',
  'press': 'press',
  'presses': 'press',
  'row': 'row',
  'rows': 'row',
  'raise': 'raise',
  'raises': 'raise',
  'fly': 'fly',
  'flys': 'fly',
  'flies': 'fly',
  'flyes': 'fly',
  'extension': 'extension',
  'extensions': 'extension',
  'extend': 'extension',
  'flexion': 'flexion',
  'squat': 'squat',
  'squats': 'squat',
  'lunge': 'lunge',
  'lunges': 'lunge',
  'crunch': 'crunch',
  'crunches': 'crunch',
  'kickback': 'kickback',
  'kickbacks': 'kickback',
  'shrug': 'shrug',
  'shrugs': 'shrug',
  'twist': 'twist',
  'twists': 'twist',
  'rotation': 'rotation',
  'rotations': 'rotation',
  'pullover': 'pullover',
  'pullovers': 'pullover',

  // Positions
  'front': 'front',
  'rear': 'rear',
  'back': 'rear',
  'posterior': 'rear',
  'anterior': 'front',
  'lateral': 'lateral',
  'side': 'lateral',
  'medial': 'medial',
  'inner': 'inner',
  'outer': 'outer',
  'wide': 'wide',
  'close': 'close',
  'narrow': 'close',
  'grip': 'grip',
  'overhand': 'overhand',
  'underhand': 'underhand',
  'supinated': 'underhand',
  'pronated': 'overhand',
  'neutral': 'neutral',
  'hammer': 'hammer',

  // Common variations
  'romanian': 'romanian',
  'rdl': 'romanian deadlift',
  'sldl': 'stiffleg deadlift',
  'stiff': 'stiffleg',
  'stiffleg': 'stiffleg',
  'stiff-leg': 'stiffleg',
  'sumo': 'sumo',
  'goblet': 'goblet',
  'bulgarian': 'bulgarian',
  'split': 'split',
  'hip': 'hip',
  'hips': 'hip',
  'leg': 'leg',
  'legs': 'leg',
  'arm': 'arm',
  'arms': 'arm',
  'skull': 'skull',
  'skulls': 'skull',
  'skullcrusher': 'skullcrusher',
  'skull-crusher': 'skullcrusher',
  'skullcrushers': 'skullcrusher',

  // Jump rope variations
  'jumprope': 'jumprope',
  'jump-rope': 'jumprope',
  'skipping': 'jumprope',
  'rope': 'jumprope',
  'jump': 'jump',
  'jumping': 'jump',

  // Plank variations
  'plank': 'plank',
  'planks': 'plank',
  'planking': 'plank',
};
